### PR TITLE
Add Hub Detect Property to Bypass Local Proxy for On Premise Hub. 

### PR DESCRIPTION
**Pull request by kms254**
# Pull Request template

**Link to github issue (if applicable):**

*  

**If nothing above, what is your reason for this pull request:**

* I have an on premise installation of Black Duck hub. External access is only available via a proxy. I need to use the proxy to pull down the latest tools but, I cannot reach the on premise installation of the Hub through the proxy. The hub detect powershell scripts set the proxy globally which does not give you the granular option of when and where the proxy should be used. This additional Hub Detect property would allow us to bypass the proxy with an on premise installation of BlackDuck Hub. 

**Changes proposed in this pull request:**

* Add a Hub Detect Property "--blackduck.hub.onpremise" 
* Property default is set to false.
* If it is true set the proxy host, port, username, password, NTLM Domain, and NTLM Workstation to null.

### CODE REVIEW

**Comment by kms254** [comment]
* What went wrong:
Execution failed for task ':sonarqube'.
> You're only authorized to execute a local (preview) SonarQube analysis without pushing the results to the SonarQube server. Please contact your SonarQube administrator.


I highly doubt this is me.... Seems like CI is broken?

**Comment by jamesrichard91** [comment]
Hey @kms254 , this is a great idea but if we are going to do this we should make it flexible. Would this PR solve the issue you are having? https://github.com/blackducksoftware/hub-detect/pull/225

**Comment by jamesrichard91** [comment]
If PR https://github.com/blackducksoftware/hub-detect/pull/225 does not solve your issue please comment on that PR and let us know!

**Comment by kms254** [comment]
@jamesrichard91  PR #225  seems to work for me and I added a note.

**Pull request closed without merging**
