### PR TITLE
Added ability to aggregate bom

### PR DESCRIPTION
**Pull request by JakeMathews**
This is my hacky attempt at getting the dependencies into one bdio. According to Ari the project metadata doesn't really matter. This new property should be exclusively used by the co-pilot folks and probably never by customers.

### CODE REVIEW

**Comment by akamen** [comment]
@JakeMathews  so this becomes another BOM Tool?

**Comment by jrichardBD** [comment]
I don't like it because it feels like we are overloading BomToolType

**Comment by JakeMathews** [comment]
The only reason it is a bom tool type is because a code location demands one. We could perhaps change that, or instead of trying to work it into the existing codeLocations, have another method for creating the bdio files given a project. Which now that I think about it, I like more.

**Comment by jrichardBD** [comment]
Couldn't we have a separate method to aggregate the code locations together?

**Pull request merged**
