### PR TITLE
ensure the scanning can be done in parallel

### PR DESCRIPTION
**Pull request by rmannibucau**
The scanning phase of blackduck is ok for a few modules but when you have several modules it is very slow and can be optimized parallelizing the scanning.

On my project with ~28 maven modules, using the default of number of processor divided by 7 the scanning time.

### CODE REVIEW

**Comment by rmannibucau** [comment]
up? this is really impacting for big projects and would be very appreciated to be released to bring the scanning from ~20mn to ~2-3mn

**Comment by jamesrichard91** [comment]
- Can we change the name of "detect.execution.parallelism" to "detect.scan.parallel.processors"

- Can we change the description to something like "The number of scans to run in parallel, default to the number of processors"

We can work these changes into the next release, but with the Holidays it may take a little while. Are you able to work with your modified version in the meantime?

**Comment by rmannibucau** [comment]
@jamesrichard91 updated the PR with these renaming. I can use the snapshot in the meantime yes. Thanks to have a look :).

**Comment by rmannibucau** [comment]
up?

**Comment by ekerwin** [comment]
We love the changes, but we are focused on other stuff right now. We should be able to merge this in Q1. Please don't let us forget!

**Comment by akamen** [comment]
@ekerwin can we slot this for 2.5.0

**Comment by ekerwin** [comment]
Finally taking a look at this - really great stuff. This will be included in the next release of hub-detect (2.5.0, code freezing next week)

**Pull request merged**
